### ISSUE TITLE
 this game was updated

### ISSUE THREAD

**Issue by chase692** [Eisbison/TheOtherRoles#314]
like to know if this mod will be updated soon as the game was updated a few days ago.. the mod no longer works

**Comment by dwd0tcom** [comment]
It works but only on custom servers. You can use **play.theotherroles.de** as a custom server. We're working on a fix!

**Comment by Keksmonster01** [comment]
is the issue fixed?

**Comment by Elujla** [comment]
This should be fixed with new version.
Right now it's still possible to play on older version of Among Us even on Innersloth servers.

**Comment by Keksmonster01** [comment]
I hope it gets fixed soon, because no matter which version you have, the bug is still there (endless lobby). It seems that the most of the players have this bug, and some not. Some of us are getting an endgame screen, but most people not. Sure, you can play on a custom server, but not even that works for every player to join. It's just really frustrating to create always a new lobby, and to join.
